version: '3'
services:
  webapp:
    build:
      context: .
    ports:
      - 8080:8080
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./devops/prometheus/prometheus-local.yml:/etc/prometheus/prometheus.yml