replicaCount: 1

image:
  repository: keyproco/echo-webapp
  pullPolicy: IfNotPresent
  tag: "1.1.0"

service:
  port: 8080
  type: NodePort 
  nodePort:  # NodePort value

autoscaling:
  enabled: false

serviceAccount:
  create: true
  name: echo-sa
ingress:
  enabled: false

prometheus:
  enabled: true
  serviceMonitor:
    namespace: default
    interval: 15s
    path: /metrics